import {
  Anchor,
  Anvil,
  Axe,
  BrickWall,
  Bone,
  BatteryCharging,
  CircleDashed,
  Cog,
  CircuitBoard,
  CookingPot,
  CupSoda,
  Droplet,
  Drumstick,
  Fish,
  Flame,
  FlameKindling,
  GlassWater,
  Grid3X3,
  Hammer,
  Gem,
  Leaf,
  Layers3,
  Microscope,
  RadioTower,
  ShipWheel,
  Package,
  Pickaxe,
  Recycle,
  Sailboat,
  ShieldCheck,
  Sprout,
  Shell,
  Citrus,
  Sword,
  TreePine,
  Waves,
  Antenna,
  AudioWaveform,
  type LucideProps,
} from 'lucide-react';
import type { ItemId } from '../game/domain/items';

const ICONS: Record<ItemId, React.ComponentType<LucideProps>> = {
  timber: TreePine,
  polymer: Recycle,
  fiber: Leaf,
  scrap: Cog,
  rope: CircleDashed,
  stone: Pickaxe,
  palmSeed: Sprout,
  sand: Shell,
  clay: Layers3,
  metalOre: Gem,
  wetBrick: BrickWall,
  dryBrick: BrickWall,
  metalIngot: Anvil,
  glassPane: Layers3,
  hinge: Cog,
  seaweed: Waves,
  sharkHide: ShieldCheck,
  sharkTooth: Bone,
  emptyCup: CupSoda,
  collectionNetKit: Grid3X3,
  purifierKit: GlassWater,
  grillKit: CookingPot,
  solarPurifierKit: GlassWater,
  tripleGrillKit: CookingPot,
  lockerKit: Package,
  sailKit: Sailboat,
  anchorKit: Anchor,
  helmKit: ShipWheel,
  stormRigKit: ShieldCheck,
  anchorBraceKit: Anchor,
  planterKit: Sprout,
  researchBenchKit: Microscope,
  smelterKit: Anvil,
  hook: Anchor,
  hammer: Hammer,
  spear: Sword,
  metalSpear: Sword,
  resonanceFork: AudioWaveform,
  fishingRod: Fish,
  axe: Axe,
  metalAxe: Axe,
  emergencyWater: Droplet,
  freshWaterCup: GlassWater,
  ration: Package,
  palmFruit: Citrus,
  rawFish: Fish,
  sharkMeat: Drumstick,
  cookedFish: Flame,
  burntFish: FlameKindling,
  signalBoard: CircuitBoard,
  brineCell: BatteryCharging,
  receiverKit: RadioTower,
  antennaKit: Antenna,
};

interface ItemIconProps extends LucideProps {
  itemId: ItemId;
}

export function ItemIcon({ itemId, ...props }: ItemIconProps) {
  const Icon = ICONS[itemId];
  return <Icon {...props} />;
}
