import {
  Anchor,
  Anvil,
  Axe,
  BrickWall,
  CircleDashed,
  Cog,
  CookingPot,
  CupSoda,
  Droplet,
  Fish,
  Flame,
  FlameKindling,
  GlassWater,
  Hammer,
  Gem,
  Leaf,
  Layers3,
  Microscope,
  ShipWheel,
  Package,
  Pickaxe,
  Recycle,
  Sailboat,
  ShieldCheck,
  Sprout,
  Shell,
  Citrus,
  Sword,
  TreePine,
  Waves,
  type LucideProps,
} from 'lucide-react';
import type { ItemId } from '../game/domain/items';

const ICONS: Record<ItemId, React.ComponentType<LucideProps>> = {
  timber: TreePine,
  polymer: Recycle,
  fiber: Leaf,
  scrap: Cog,
  rope: CircleDashed,
  stone: Pickaxe,
  palmSeed: Sprout,
  sand: Shell,
  clay: Layers3,
  metalOre: Gem,
  wetBrick: BrickWall,
  dryBrick: BrickWall,
  metalIngot: Anvil,
  seaweed: Waves,
  emptyCup: CupSoda,
  purifierKit: GlassWater,
  grillKit: CookingPot,
  sailKit: Sailboat,
  anchorKit: Anchor,
  helmKit: ShipWheel,
  stormRigKit: ShieldCheck,
  planterKit: Sprout,
  researchBenchKit: Microscope,
  smelterKit: Anvil,
  hook: Anchor,
  hammer: Hammer,
  spear: Sword,
  metalSpear: Sword,
  fishingRod: Fish,
  axe: Axe,
  metalAxe: Axe,
  emergencyWater: Droplet,
  freshWaterCup: GlassWater,
  ration: Package,
  palmFruit: Citrus,
  rawFish: Fish,
  cookedFish: Flame,
  burntFish: FlameKindling,
};

interface ItemIconProps extends LucideProps {
  itemId: ItemId;
}

export function ItemIcon({ itemId, ...props }: ItemIconProps) {
  const Icon = ICONS[itemId];
  return <Icon {...props} />;
}
